const HTTP_ACTION_TYPES = {
    START: "HTTP_REQUEST_START",
    END: "HTTP_REQUEST_END",
    REQUEST_FAILED: "HTTP_REQUEST_FAILED",
}

const POST_ACTION_TYPES = {
    LOAD: "LOAD_ALL_POSTS"
}

const USER_ACTION_TYPES = {
    GET: "GET_USER"
}
const APP_ACTION_TYPES = {
    NAVBAR: "TOGGLE_NAVBAR"
}

export {
    HTTP_ACTION_TYPES,
    POST_ACTION_TYPES,
    USER_ACTION_TYPES,
    APP_ACTION_TYPES
};
