export enum HTTP_METHOD {
    POST = "POST",
    GET = "GET",
    UPDATE = "PUT",
    REMOVE = "DELETE",
}

export enum HTTP_ACTIONS {
    START = "HTTP_REQUEST_START",
    END = "HTTP_REQUEST_END",
    REQUEST_FAILED = "HTTP_REQUEST_FAILED",
}
